UnauthorizedError = Exception('we failed to provide a correct auth_token. are you logged in?')
